<!-- 聊天窗口 -->
<template>
  <div class="chat-viewer">
    <div class="chat-title">
      <div class="flex-center">
        <img
          src="https://t7.baidu.com/it/u=4162611394,4275913936&fm=193&f=GIF"
          alt="头像"
          class="avatar"
        />
        <span class="nickname">Cyndi Wang</span>
      </div>
      <div class="coin" @click="chargeStore.showCharge = true">
        <img src="~/assets/images/a9.webp" alt="金币图标" />
        <span>86.72</span>
      </div>
    </div>

    <div class="scroll-area" @scroll="onLoadHistory">
      <!-- <div class="chat-box"> -->
      <a-spin class="loading" :size="18" v-show="chatStore.isLoadingMore" />
      <div class="tip" pc>Content generated by AI @xxx</div>
      <div class="tip" mobile>
        All chats and related services are Al-generated, and some may incur
        charges. Please ensure sufficient balance.
      </div>
      <div
        class="chat-item"
        v-for="message in chatStore.chatHistory"
        :key="message.id"
        :class="{ message_right: message.role === 'user' }"
      >
        <!-- 用户消息 -->
        <div
          v-if="message.role === 'user'"
          class="user-message"
          v-html="message.context.replace(/\\n/g, '<br/>')"
        ></div>

        <!-- 机器人消息 -->
        <Chat-Bubble
          v-else
          :type="message.dataType"
          :content="message.context"
        />
      </div>
      <!-- </div> -->
    </div>

    <!-- 底部输入区域 -->
    <Chat-Input />
  </div>
</template>

<script setup lang="ts">
import { useChatStore } from '~/stores/chat.store'
import { useChargeStore } from '~/stores/charge.store'

const chatStore = useChatStore()
const chargeStore = useChargeStore()

// 上滑加载更多聊天记录
const onLoadHistory = (event: any) => {
  if (event.target.scrollTop < 20) chatStore.fetchChatHistory()
}
</script>

<style scoped lang="scss">
.chat-viewer {
  height: 100%;
  padding: 0 0.15rem;
  background-color: #111111;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  .chat-title {
    width: 100%;
    padding-top: 0.185rem;
    padding-bottom: 0.18rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #111111;
    .avatar {
      width: 0.45rem;
      height: 0.45rem;
      margin-right: 0.12rem;
      border-radius: 50%;
      overflow: hidden;
      object-fit: cover;
    }
    .nickname {
      font-size: 0.195rem;
      font-weight: 600;
      line-height: 1;
      font-variation-settings: 'opsz' auto;
      color: #ffffff;
    }

    .coin {
      width: fit-content;
      height: 0.25rem;
      padding: 0 0.04rem;
      border-radius: 0.16rem;
      background: rgba(255, 255, 255, 0.3);
      display: flex;
      align-items: center;
      white-space: nowrap;
      cursor: pointer;
      img {
        width: 0.2rem;
        height: 0.2rem;
        margin-right: 0.01rem;
      }
      span {
        font-size: 0.13rem;
        font-weight: 500;
        color: #ffffff;
      }
    }
  }

  .scroll-area {
    width: 100%;
    padding-bottom: 1rem;
    flex: 1;
    overflow-y: scroll;
    &::-webkit-scrollbar {
      display: none;
    }
    // .chat-box{
    //   width: 100%;
    //   height: fit-content;
    // }
    .loading {
      width: 100%;
      text-align: center;
    }
    .tip {
      width: 100%;
      margin-bottom: 0.18rem;
      margin-top: 0.24rem;
      font-size: 0.15rem;
      font-weight: 400;
      line-height: 0.1275rem;
      text-align: center;
      font-variation-settings: 'opsz' auto;
      color: rgba(255, 255, 255, 0.5);
      &[mobile] {
        display: none;
      }
    }
    .chat-item {
      width: 100%;
      margin-bottom: 0.105rem;
    }
    .message_right {
      display: flex;
      justify-content: flex-end;

      .user-message {
        width: fit-content;
        max-width: 70%;
        height: fit-content;
        min-height: 0.4425rem;
        margin: 0.075rem 0;
        border-radius: 0.18rem;
        padding: 0.12rem;
        background: #343434;
        font-size: 0.1575rem;
        font-weight: 400;
        line-height: 0.2025rem;
        color: rgba(255, 255, 255, 0.9);
        word-break: break-all;
        overflow: hidden;
      }
    }
  }
}

@media screen and (max-width: 480px) {
  .chat-viewer {
    width: 100%;
    height: 100%;
    padding: 0 4.2667vw;
    background-color: #111111;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    .chat-title {
      width: 100%;
      padding-top: 2.6667vw;
      padding-bottom: 2.6667vw;
      display: flex;
      justify-content: space-between;
      align-items: center;
      background-color: #111111;
      .avatar {
        width: 8.5333vw;
        height: 8.5333vw;
        margin-right: 1.8667vw;
        border-radius: 50%;
        overflow: hidden;
        object-fit: cover;
      }
      .nickname {
        font-size: 4.2667vw;
        font-weight: 600;
        line-height: 1;
        font-variation-settings: 'opsz' auto;
        color: #ffffff;
      }

      .coin {
        width: fit-content;
        height: 5.8667vw;
        padding: 0 1.0667vw;
        border-radius: 4.2667vw;
        background: rgba(255, 255, 255, 0.3);
        display: flex;
        align-items: center;
        white-space: nowrap;
        cursor: pointer;
        img {
          width: 4.2667vw;
          height: 4.2667vw;
          margin-right: 0.2667vw;
        }
        span {
          font-size: 2.9333vw;
          font-weight: 500;
          color: #ffffff;
        }
      }
    }

    .scroll-area {
      width: 100%;
      padding-bottom: 26.6667vw;
      flex: 1;
      overflow-y: scroll;
      &::-webkit-scrollbar {
        display: none;
      }
      .loading {
        width: 100%;
        text-align: center;
      }
      .tip {
        width: 100%;
        padding: 0 8.5333vw;
        margin-bottom: 8.5333vw;
        margin-top: 1.0667vw;
        font-size: 3.2vw;
        font-weight: 400;
        line-height: 5.3333vw;
        text-align: center;
        font-variation-settings: 'opsz' auto;
        color: #afafaf;
        &[pc] {
          display: none;
        }
        &[mobile] {
          display: block;
        }
      }
      .chat-item {
        width: 100%;
        margin-bottom: 1.0667vw;
      }
      .message_right {
        display: flex;
        justify-content: flex-end;

        .user-message {
          width: fit-content;
          max-width: 70%;
          height: fit-content;
          min-height: 11.7333vw;
          margin: 3.2vw 0;
          border-radius: 5.3333vw;
          padding: 3.2vw 4.2667vw;
          background: #343434;
          font-size: 3.7333vw;
          font-weight: 400;
          line-height: 5.3333vw;
          color: rgba(255, 255, 255, 0.9);
          word-break: break-all;
          overflow: hidden;
        }
      }
    }
  }
}
</style>
